#!/bin/sh
# © 2013 Cyril Brulebois <kibi@debian.org>
set -e

mail=kibi@debian.org
workdir=${1:-edos.tmp}
www=$2

# Generate report and dot files:
index=index.html
diff=diff.txt
./edos4udebs --workdir $workdir --mail $mail --index $index --diff $diff

# Generate graphs:
for i in $workdir/*.dot; do
  dot -Tpng $i -o ${i%%.dot}.png
done

# Publish:
if [ ! -z "$www" ]; then
  rsync -a $workdir/$index $workdir/$diff $workdir/*.png $www/
fi
